POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNyeXB0b2giLCJpZCI6IjY1ZmJiYzgwMmE2MjYwMTU5ZTZhZTg5MSIsImlhdCI6MTcxMTAwMjAyN30.AcFR_xCxDcAB1_0K1hY54upusOBbPPL8fMPt8RKHVDA

{
"title": "Hayfever Sux!",
"author": "Sneezy Joe",
"url": "www.snotboizzz.com",
"likes": "1738",
"userId": "65fba2971090d594caaa3025"
}
